registry: true
registry_keys:
  - "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList"
  - "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
browsers:
  chrome: true
  firefox: true
  edge: true
event_logs:
  system: true
  security: true
  application: false
mft: true
